---
# tasks file for aws-workspacesclient
- name: Add AWS workspacesclient
  apt_key:
    url: https://workspaces-client-linux-public-key.s3-us-west-2.amazonaws.com/ADB332E7.asc
    state: present
  become: yes

- name: Add AWS workspacesclient apt repository
  apt_repository:
    repo: deb [arch=amd64] https://d3nt0h4h6pmmc4.cloudfront.net/ubuntu bionic main
  become: yes

- name: Install workspacesclient
  apt:
    name: ['workspacesclient']
    state: present
  become: yes
