---
# tasks file for vscode

- name: Add microsoft key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    state: present

- name: Add microsoft apt repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install VSCode
  apt:
    name: ['code']
    state: latest

- name: Register extensions
  command: code --list-extensions
  register: extensions
  become: no

- name: Install golang.go extension
  command: code --install-extension golang.go
  become: no
  when: extensions.stdout_lines is not search('golang.go')

#- debug:
#    var: extensions.stdout_lines
