---
# tasks file for vscode

- name: Add microsoft key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add microsoft apt repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install VSCode
  apt:
    name: ['code']
    state: present
