---

- name: Configure
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Create ~/Projects directory
    file:
      path: ~/Projects
      state: directory

  - name: Install OpenVPN helper script
    git: 
      repo: git@github.com:anderskvist/openvpn-script.git
      dest: ~/Projects/openvpn-script


# i3 config
  - name: Create ~/.config/i3
    file:
      path: ~/.config/i3
      state: directory

  - name: Symlink i3 config
    file:
      src: ~/Projects/workstation-config/i3/config
      dest: ~/.config/i3/config
      state: link

# scripts
  - name: Create ~/bin directory
    file:
      path: ~/Projects
      state: directory

  - name: Find scripts
    find:
      paths: ~/Projects/workstation-config/scripts
    register: scripts_found

  - name: Symlink for all scripts to ~/bin
    file:
      src: "{{ item.path }}"
      dest: "~/bin/{{ item.path | basename }}"
      state: link
    with_items: "{{ scripts_found.files }}"
