---

- name: Configure
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Create ~/Projects directory
    file:
      path: ~/Projects
      state: directory

  - name: Install OpenVPN helper script
    git: 
      repo: git@github.com:anderskvist/openvpn-script.git
      dest: ~/Projects/openvpn-script


# i3 config
  - name: Create ~/.config/i3
    file:
      path: ~/.config/i3
      state: directory

  - name: Symlink i3 config
    file:
      src: ~/Projects/workstation-config/i3/config
      dest: ~/.config/i3/config
      state: link

# scripts
  - name: Create ~/bin directory
    file:
      path: ~/Projects
      state: directory

  - name: Find scripts
    find:
      paths: ~/Projects/workstation-config/scripts
    register: scripts_found

  - name: Symlink for all scripts to ~/bin
    file:
      src: "{{ item.path }}"
      dest: "~/bin/{{ item.path | basename }}"
      state: link
    with_items: "{{ scripts_found.files }}"

# lock screen when suspending
# https://hund0b1.gitlab.io/2019/01/08/using-i3lock-with-systemd-suspend.html
  - name: Create systemd service
    become: yes
    copy:
      dest: /etc/systemd/system/i3lock.service
      content: |
        [Unit]
        Description=Lock screen before suspend
        Before=sleep.target

        [Service]
        User=akv
        Type=forking
        Environment=DISPLAY=:0
        ExecStart=/home/akv/bin/lock_screen.sh

        [Install]
        WantedBy=sleep.target

  - name: enable i3lock.service to make sure we lock the screen prior to suspend
    become: yes
    systemd:
      name: i3lock.service
      enabled: yes

# udev screen (un)plug rule
  - name: Create udev rule for screen (un)plugging
    become: yes
    copy:
      dest: /etc/udev/rules.d/99-screen-unplug.rules
      content: |
        ACTION=="change", SUBSYSTEM=="drm", ENV{HOTPLUG}=="1", RUN+="/home/akv/bin/switch_monitor.sh udev"

# enable backlight in xorg
  - name: Copy xorg.conf config
    become: yes
    copy:
      src: ~/Projects/workstation-config/X11/xorg.conf
      dest: /etc/X11/xorg.conf

# clusterssh
  - name: Create ~/.clusterssh
    file:
      path: ~/.clusterssh
      state: directory

  - name: Symlink clusterssh config
    file:
      src: ~/Projects/workstation-config/clusterssh/config
      dest: ~/.clusterssh/config
      state: link

# enable pcspkr
  - name: Comment out blacklisting of pcspkr module
    become: yes
    replace:
      path: /etc/modprobe.d/blacklist.conf
      regexp: '^blacklist pcspkr$'
      replace: '# blacklist pcspkr'
  - name: Load pcspkr module
    become: yes
    modprobe:
      name: pcspkr
      state: present

# cronjobs
  - name: Run battery status check every minute
    cron:
      name: "Battery status check"
      job: "~/bin/battery.sh"

# custom battery jobs
  - name: Create ~/bin/battery.d/ directory
    file:
      path: ~/bin/battery.d/
      state: directory
  - name: Symlink beep.sh to ~/bin/battery.dk/beep (no extension)
    file:
      src: ~/bin/beep.sh
      dest: ~/bin/battery.d/beep
      state: link

# background image
  - name: Copy background image
    copy:
      src: ~/Projects/workstation-config/background.png
      dest: ~/.background.png

# GnuCash in danish
  - name: Create GnuCash .desktop file
    copy:
      dest: ~/.local/share/applications/gnucash.desktop
      content: |
        [Desktop Entry]
        Type=Application
        MimeType=application/x-gnucash;
        Name=GnuCash Dansk
        Exec=env LANGUAGE=da_DK gnucash

# Add current user to groups
  - name: adding current user to group docker and dialout
    become: yes
    user:
      name: '{{ ansible_user_id }}'
      groups: ['docker','dialout']
      append: yes
