---

- name: Packages
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks: 

# Window Manager
  - name: Install basic packages for i3
    apt:
      name: ['i3-wm', 'scrot', 'udiskie', 'numlockx', 'i3status', 'i3lock', 'acpi', 'xautolock', 'xbacklight', 'dmenu', 'feh']
      state: present


# Applications
  - name: Install applications
    apt:
      name: ['clusterssh','emacs-nox','openssh-server','openvpn','git','nodejs','npm','nmap','whois','vlc','virt-manager','pwgen','mc','screen','geeqie','curl','beep','lxpolkit','gnucash','openscad','inkscape','librecad']
      state: present


# Docker
  - name: Add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable edge test

  - name: Install docker
    apt:
      name: ['docker-ce','python-pip']
      state: present

  - name: Install docker-compose
    pip:
      name: docker-compose


# Spotify
  - name: Add spotify apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90

  - name: Add spotify apt repository
    apt_repository:
      repo: deb http://repository.spotify.com stable non-free

  - name: Install spotify client
    apt:
      name: ['spotify-client']


# Google chrome
  - name: Add google-chrome apt key
    apt_key:
       url: https://dl-ssl.google.com/linux/linux_signing_key.pub

  - name: Add google-chrome apt repository
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

  - name: Install google-chrome
    apt:
      name: ['google-chrome-stable']

# Balena Etcher
  - name: Add Etcher apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 379CE192D401AB61

  - name: Add Etcher apt repository
    apt_repository:
      repo: deb https://deb.etcher.io stable etcher

  - name: Install Etcher
    apt:
      name: ['balena-etcher-electron']

# golang
  - name: Add golang PPA
    apt_repository:
      repo: ppa:longsleep/golang-backports

  - name: Install golang
    apt:
      name: ['golang-go']

# Atom IDE
  - name: Add Atom apt key
    apt_key:
      url: https://packagecloud.io/AtomEditor/atom/gpgkey

  - name: Add Atom apt repository
    apt_repository:
      repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main

  - name: Install Atom
    apt:
      name: ['atom']

# Arduino IDE
  - name: Fetch and extract Arduino IDE in /opt
    unarchive:
      src: https://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz
      dest: /opt
      creates: /opt/arduino-1.8.9
      remote_src: yes

  - name: Install Arduino IDE
    shell: /opt/arduino-1.8.9/install.sh
    args:
      creates: /usr/local/bin/arduino

# Cura
  - name: Fetch Cura appimage
    get_url:
      url: https://github.com/Ultimaker/Cura/releases/download/4.1.0/Ultimaker_Cura-4.1.0.AppImage
      dest: /opt/Ultimaker_Cura-4.1.0.AppImage
      mode: '0755'

  - name: Create Cura .desktop file
    copy:
      dest: /usr/share/applications/cura.desktop
      content: |
        [Desktop Entry]
        Type=Application
        Name=Cura
        Comment=Slicer software
        Exec=/opt/Ultimaker_Cura-4.1.0.AppImage

  - name: Fetch Cura appimage
    get_url:
      url: https://github.com/Ultimaker/Cura/releases/download/3.5.1/Cura-3.5.1.AppImage
      dest: /opt/Cura-3.5.1.AppImage
      mode: '0755'

# NextCloud
  - name: Fetch NextCloud appimage
    get_url:
      url: https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.5.2-x86_64.AppImage
      dest: /opt/Nextcloud-2.5.2-x86_64.AppImage
      mode: '0755'

  - name: Create NextCloud .desktop file
    copy:
      dest: /usr/share/applications/nextcloud.desktop
      content: |
        [Desktop Entry]
        Type=Application
        Name=NextCloud
        Comment=DropBox clone
        Exec=/opt/Nextcloud-2.5.2-x86_64.AppImage
