---

- name: playbook
  hosts: 127.0.0.1
  connection: local

  roles:
  - role: zoom
    become: yes
  - role: vscode
    become: yes
  - role: spotify
    become: yes

#- import_playbook: _packages.yml
#- import_playbook: _config.yml
