---
# tasks file for gnucash

- name: Install GnuCash
  apt:
    name: ['gnucash']
    state: present

# GnuCash in danish
- name: Create GnuCash .desktop file
  copy:
    dest: ~/.local/share/applications/gnucash.desktop
    content: |
      [Desktop Entry]
      Type=Application
      MimeType=application/x-gnucash;
      Name=GnuCash Dansk
      Exec=env LANGUAGE=da_DK gnucash
